### ISSUE TITLE
The keyword argument not understood: 'transposed'

### ISSUE THREAD

**Issue by overlord000** [JesperDramsch/Complex-CNN-Seismic#1]
The code     
model.add(complexnn.conv.ComplexConv2D(2 ** (x + 4), (3, 3), strides=(2, 2), transposed=True, activation=act_fn, padding='same'))
in line 34 of mass_train.py has an extra keyword "transposed", could you give out the reliable function file?

**Comment by JesperDramsch** [comment]
`pip install keras-complex`
